# Generated by Django 2.1.7 on 2021-01-03 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210102_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 2, 23, 33, 50, 555602)),
        ),
    ]
